export interface Specialization {
  category: string;
  items: string[];
}

export const specializations: Specialization[] = [
{
  category: "Acabados",
  items: [
    "Accesorios de baño",
    "Adecuaciones y remodelaciones",
    "Alfombrado",
    "Aseo",
    "Carpintería de madera",
    "Carpintería de aluminio",
    "Carpintería metálica",
    "CCTV",
    "Citofonía",
    "Climatización",
    "Construcciones livianas (Drywall y Superboard)",
    "Cortinas y persianas",
    "Cubiertas y terrazas",
    "Divisiones de baño y espejos",
    "Domótica",
    "Equipamiento baño",
    "Equipamiento cocina",
    "Equipos especiales zonas comunes",
    "Electrodomésticos y gasodomésticos",
    "Enchapes",
    "Herrería ornamental",
    "Iluminación",
    "Impermeabilización y aislamiento térmico",
    "Jardinería y sistema de riego",
    "Limpieza de fachadas",
    "Mármoles y granitos",
    "Mesones",
    "Mobiliario",
    "Mobiliario de oficina",
    "Mobiliario exterior",
    "Mobiliario sanitario",
    "Muros móviles",
    "Paneles de techo y pared",
    "Parques infantiles",
    "Pavimento y entablado de madera",
    "Persianas y rejillas de ventilación",
    "Pintura dry fall",
    "Pintura en muros",
    "Piso laminado",
    "Puertas de madera",
    "Puertas enrollables",
    "Puertas metálicas",
    "Revestimientos",
    "Señalización y nomenclatura",
    "Shut de basuras",
    "Tabiques de baño",
    "Tejas de techo",
    "Vallas y puertas de malla metálica",
    "Ventanería"
  ]
},
{
  category: "Diseño de proyectos",
  items: [
    "Asesoría HQE",
    "BIM",
    "Caseta de ventas o depto. de muestra",
    "Certificación ambiental HQE",
    "Coordinación de planeación",
    "Diseño acústico",
    "Diseño arquitectónico",
    "Diseño bioclimático",
    "Diseño calentamiento de agua",
    "Diseño de iluminación",
    "Diseño eléctrico",
    "Diseño elementos no estructurales",
    "Diseño estructural",
    "Diseño hidrosanitario + RCI + gas",
    "Diseño HVAC",
    "Diseño interior",
    "Diseño piscina",
    "Diseño planta de tratamiento",
    "Estudio de suelos",
    "Estudio seguridad humana",
    "Ingeniería acústica",
    "Ingeniería de costos",
    "Ingeniería de fachadas",
    "Ingeniería de multimedia",
    "Ingeniería de señalización",
    "Ingeniería de taludes",
    "Ingeniería MEP",
    "Ingeniería y asesoría estructural",
    "Interiorismo",
    "Levantamiento topográfico",
    "Marketing y Publicidad",
    "Paisajismo",
    "Presupuesto",
    "Revisión estructural",
    "Seguridad y control",
    "Tecnología",
    "Tráfico vertical",
  ]
},
{
  category: "Equipamiento especiales",
  items: [
    "Balanzas",
    "Cámaras de refrigeración y congelación",
    "Chute de basura",
    "Cocinas industriales",
    "Equipamiento para muelles de carga",
    "Equipo",
    "Equipos de Procesamiento y Tanques de Acero",
    "Grúas y Polipastos",
    "Membranas tensadas y velarios",
    "Molinetes",
    "Pozos de agua",
    "Seguridad electrónica",
  ]
},
{
  category: "Estudios",
  items: [
    "Estudio de impacto ambiental",
    "Estudio de impacto vial",
    "Estudio de transporte vertical",
    "Estudio de vientos",
    "Estudio geológico",
    "Estudio hidrológico",
    "Ingeniería estructural",
    "Levantamiento fotográfico",
    "Levantamiento topográfico",
    "Mecánica de suelos",
    "Rasantes",
    "Revisor estructural",
  ]
},
{
  category: "Ferreterías",
  items: [
    "Accesorios de baño",
    "Accesorios de cocina",
    "Acero",
    "Aditivos, adhesivos y químicos",
    "Aluminio y vidrio",
    "Aparatos eléctricos",
    "Cancelería",
    "Cerraduras, herrajes y candados",
    "Cerramientos",
    "Combustibles y lubricantes",
    "Durmientes",
    "Estucos, pinturas y revestimientos",
    "Herramientas menores",
    "Impermeabilizantes",
    "Maderas y plásticos",
    "Material general de ferretería",
    "Perfilería",
    "Piedras",
    "Puertas metálicas",
    "Puertas seccionales",
    "Puertas y ventanas",
    "Redes de gas",
    "Rejillas",
    "Secantes",
    "Seguridad industrial y dotación",
    "Sogas y cadenas",
    "Tornillería y fijaciones",
    "Tubería eléctrica",
    "Tubería hidráulica y sanitaria",
  ]
},
{
  category: "Gerencia, auditoría e indirectos",
  items: [
    "Administración provisional",
    "Consultoría",
    "Auditoría externa",
    "Auditoría interna",
    "Fianzas",
    "Gerencia de construcción",
    "Gerencia de proyecto",
    "Inmobiliaria",
    "Interventoría",
    "Lean construction",
    "Postventa",
    "Revisión de proyectos",
    "Seguros",
    "Servicio caseta de obra",
    "Servicios proyecto",
    "Supervisión",
    "Supervisión técnica",
  ]
},
{
  category: "Obra",
  items: [
    "Aceros, mallas y alambres",
    "Afinado de piso",
    "Aire acondicionado y calefacción",
    "Aire comprimido",
    "Albañilería",
    "Alberca y cuerpos de agua",
    "Alcantarillado",
    "Alistado de pisos",
    "Alquiler y compra de maquinaria",
    "Ascensores y escaleras metálicas",
    "Bandas transportadoras",
    "Báscula camioneta",
    "Bloque, ladrillo y adoquín",
    "Carpeta asfáltica",
    "Caseta de guardias",
    "Cerramiento perimetral",
    "Cimbra, acero de refuerzo y concreto",
    "Cimentaciones",
    "Concreto, cemento y mortero",
    "Concreto prefabricado",
    "Concreto proyectado",
    "Construcciones especiales",
    "Control de calidad de materiales",
    "Cuartos fríos",
    "Demolición",
    "Elevadores",
    "Ensamblajes de tablero de yeso",
    "Ensayos, laboratorios y muestras",
    "Entablado de techo de acero y entablado de piso",
    "Equipo de anden",
    "Equipos de bombeo",
    "Equipos de presión",
    "Equipos hidráulicos",
    "Equipos para trabajo en alturas",
    "Escenarios deportivos (Gimnasios, canchas múltiples, squash, etc.)",
    "Especiales (equipos especiales)",
    "Estructura",
    "Estructura de acero",
    "Estructura de concreto",
    "Estructura metálica",
    "Estructura metálica y laminación",
    "Excavación y relleno",
    "Fachada ventilada",
    "Filtros",
    "Firmes",
    "Formaleta",
    "Gas Natural",
    "Grúas viajeras",
    "Hierro dúctil",
    "Indirectos de obra",
    "Instalación eléctrica",
    "Instalación mecánica",
    "Instalaciones de gases",
    "Madera común",
    "Malla ciclónica",
    "Mampostería",
    "Material de cantera y agregados",
    "Mejora de suelos Muros de contención",
    "Montaje de lineas de transmisión y subestaciones",
    "Movimiento de tierra",
    "Muros precolados y Tilt-Up",
    "Nivelación de terrenos",
    "Obra civil",
    "Pailería",
    "Pañetes",
    "Pavimentos asfálticos",
    "Pavimentos resilientes",
    "Piscinas y zonas húmedas",
    "Pilotaje",
    "Pisos de concreto",
    "Pisos elevados",
    "Pisos recubiertos",
    "Plan de Manejo de Tránsito (PMT)",
    "Planta eléctrica",
    "Plomería",
    "Preliminares",
    "Protección de caidas",
    "Red contraincendio",
    "Red de gas",
    "Redes eléctricas",
    "Redes hidrosanitarias",
    "Remodelaciones y adecuaciones",
    "Sistemas constructivos",
    "Sistema contra incendio",
    "Subestación",
    "Tanques",
    "Techos",
    "Tendido",
    "Terracerías",
    "Terracerías y obras exteriores",
    "Topografía",
    "Trasiegos",
    "Urbanismo",
  ]
},
{
  category: "Recusos Humanos",
  items: [
    "Bienestar",
    "Desarrollo",
    "Evaluación",
    "Formación",
  ]
},
{
  category: "Insumos para oficina",
  items: [
    "Papelería, aseo y cafetería",
  ]
},
{
  category: "Servicios",
  items: [
    "Mantenimiento",
    "Publicitarios",
    "Tecnología",
    "Transporte",
    "Vigilancia",
  ]
}
];
